# Generated by Django 4.1 on 2023-12-13 10:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_car_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="phoneNumber",
            field=models.CharField(max_length=11, default=''),
            preserve_default=False,
        ),
    ]
