# Generated by Django 4.1 on 2023-12-13 10:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_car_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="phoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, null=True, region=None
            ),
        ),
    ]
