# Generated by Django 4.1 on 2023-12-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_car_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="phoneNumber",
            field=models.CharField(default="", max_length=11),
            preserve_default=False,
        ),
    ]
